language: php

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*
  - SYMFONY_VERSION=4.2.*
  - SYMFONY_VERSION=4.3.*

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - composer require -n --prefer-dist "symfony/symfony:${SYMFONY_VERSION}"

script:
  - php -v
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)
